package com.valvdata;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.valvdata.dao.DBConnection;



@WebServlet("/registerPage")
public class RegisterControl extends HttpServlet {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6910386902276155391L;
	PreparedStatement  pstmt=null;
	Connection con=null;
	Statement  stmt=null;
	ResultSet rst=null;
	public void service(HttpServletRequest request, HttpServletResponse response)
			throws IOException, ServletException {
		try {
			String email=request.getParameter("email").trim();
			String pwd=request.getParameter("pwd").trim();
			String fullName=request.getParameter("fullName").trim();
			String dateOfbirth=request.getParameter("dateOfbirth").trim();
			String designation=request.getParameter("designation").trim();
			String experiance=request.getParameter("experiance").trim();
			String mobilemumber=request.getParameter("mobilemumber").trim();
			String creationDate=request.getParameter("creationDate").trim();
			String id=request.getParameter("id").trim();
			
	     
		     
			
			System.out.println("CreationDate Priniting here "+creationDate.substring(0,16));
			ServletContext context=getServletContext(); 
			
			//Database Insertion Logic Here
			con = DBConnection.getInstance().getConnection(context.getInitParameter("db_url"),context.getInitParameter("db_username"),context.getInitParameter("db_password"));
			stmt=con.createStatement();
			PrintWriter pw=response.getWriter();
			boolean isUserExists=isUserExists(email,mobilemumber);
			
			if(!isUserExists) //if user is not registered 
			{
			pstmt=con.prepareStatement("insert into valv_users(fullname,email,dob,password,id,designation,experiance,mobilenumber,creationdate,role) values(?,?,?,?,?,?,?,?,?,?)");
			pstmt.setString(1,fullName);
			pstmt.setString(2,email);
			pstmt.setString(3, dateOfbirth);
			pstmt.setString(4, pwd);
			pstmt.setString(5,id);
			pstmt.setString(6,designation);
			pstmt.setString(7,experiance);
			pstmt.setString(8, mobilemumber);
			pstmt.setString(9, creationDate.substring(0,16));
			pstmt.setString(10,"user");
			int i=pstmt.executeUpdate();
			
			System.out.println("Reached here to the backend "+email+pwd);
			String mailBody ="Hi,<br><br>"+"<div style='color:#0000FF'>Welcome to ValvData</div>"
			        +"<br>Congrtas <b> "+fullName+"</b>  You have Successfully Registered For Valdata</br>"
					+"<br><br> <b>This is Autogenerted mail, please don't reply for this</b><br><br>"
			    +"<br><br>Regards<br/><b>ValvdataAdmin</b>";
			
			
			if(context.getInitParameter("mailflag")=="true")
			 new Sendmail().sendemailevent(context.getInitParameter("fromamail"), email, context.getInitParameter("cc"),context.getInitParameter("bcc"),"ValvData Registration(AutoGeneratedMail)", mailBody, "");
			if(i==1)
			pw.write("true");
			else
		    pw.write("false");
			
			pstmt.close();
			}
			else
				pw.write("duplicate");
			pw.flush();
			
			con.close();
			
		} catch (Exception e) {
			e.printStackTrace();
		}
	}


	public boolean isUserExists(String email,String mobilenumber)
	{ 
		boolean isUserThere=false;
		try
		{
			
			System.out.println("======Entered Here============");
			//verify the subject name
			String sql="select count(*) from valv_users where email="
					+ "'" + email + "'" + " OR mobilenumber=" + "'" + mobilenumber + "'";
			rst = stmt.executeQuery(sql);
			rst.next();
			
			System.out.println(sql); 
			if(rst.getInt(1)!=0)
				isUserThere=true;
			System.out.println("isUserThere"+rst.getInt(1));
			
		}
		catch(Exception e)
		{
			e.printStackTrace();
		}
		return isUserThere;
	}

}
